- hosts: masters[0]
  gather_facts: no

  tasks:
    - name: Get Join Command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: set join command
      set_fact:
        join_command: "{{ join_command.stdout_lines[0] }}"

- hosts: nodes
  become: yes

  vars:
    servers: "{{ groups['masters'] }}"
    join_command: "{{ hostvars[servers[0].join_command }}"

  roles:
    - hosts
    - k8s-common
    - k8s-nodes