- hosts: "{{ groups['masters'][0] }}"
  gather_facts: no
  become: yes
  become_user: root

  tasks:
    - name: Get Join Command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Get Nodes
      command: kubectl get nodes
      register: get_nodes

    - name: Set Join Command
      set_fact:
        join_command: "{{ join_command.stdout_lines[0] }}"

    - name: Set Get Nodes
      set_fact:
        get_nodes: "{{ get_nodes.stdout }}"

- hosts: nodes
  become: yes
  vars:
    servers: "{{ groups['masters'] }}"
    join_command: "{{ hostvars[servers[0]].join_command }}"
    get_nodes: "{{ hostvars[servers[0]].get_nodes }}"
  roles:
    - common
    - k8s-common
    - k8s-nodes