- hosts: masters
  become: yes
  serial: 1
  vars:
    kubeadm_version: "1.22.0-00"
    k8s_version: "v1.22.0"
    servers: "{{ groups['masters'] }}"
  roles:
    - upgrade-masters
  tags:
    - master
