- hosts: masters
  become: yes
  serial: 1
  vars:
    kubeadm_version: "1.18.10-00"
    k8s_version: "v1.18.10"
    servers: "{{ groups['masters'] }}"
  roles:
    - upgrade-masters
  tags:
    - master

- hosts: nodes
  become: yes
  serial: 1
  vars:
    kubeadm_version: "1.18.10-00"
    k8s_version: "v1.18.10"
    servers: "{{ groups['masters'] }}"
  roles:
    - upgrade-nodes
  tags:
    - nodes
