- name: Get cert key
  shell: kubeadm init phase upload-certs --upload-certs
  register: cert_key
  changed_when: no
  when: "servers[0] in ansible_fqdn"

- name: Get join command
  shell: kubeadm token create --print-join-command
  register: join_command
  changed_when: no
  when: "servers[0] in ansible_fqdn"

- name: Set cert key
  set_fact:
    cert_key_local: "{{ cert_key.stdout_lines[2] }}"
  when: "servers[0] in ansible_fqdn"

- name: Set join command
  set_fact:
    join_command_local: "{{ join_command.stdout_lines[0] }}"
  when: "servers[0] in ansible_fqdn"

- name: Masters join
  vars:
    - join: "{{ hostvars[servers[0]].join_command_local }}"
    - cert: "{{ hostvars[servers[0]].cert_key_local }}"
  command: "{{ join }} --control-plane --certificate-key {{ cert }} "
  when: "servers[0] not in ansible_fqdn"