- name: Install Keepalived
  apt:
    name: keepalived
    state: present

- name: Keepalived config
  vars:
    servers: "{{ groups['masters'] }}"
  template:
    src: keepalived/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  register: conf_change

- name: Keepalived restart
  systemd:
    state: restarted
    name: keepalived
  when: conf_change is changed

- name: Keepalived running
  systemd:
    state: started
    name: keepalived