- name: Check if Weave is being used
  shell: docker ps | grep weave
  register: weave_running
  ignore_errors: True

- name: Install Weave CNI plugin
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  when:
    - "servers[0] in ansible_fqdn"
    - weave_running.stderr