- name: Update hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    regexp: '.*{{ item }}$'
  with_items: "{{ groups.all }}"

- name: Update hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Check if cmdline.txt exists
  stat:
    path: /boot/firmware/cmdline.txt
  register: cmdline_stat

- name: Check if cmdline.txt exists
  stat:
    path: /boot/firmware/nobtcmd.txt
  register: nobtcmd_stat

- name: Enable memory control group subsystem nobtcmd.txt
  replace:
    path: /boot/firmware/nobtcmd.txt
    regexp: '(fixrtc)$'
    replace: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  register: reboot_required
  when: nobtcmd_stat.stat.exists

- name: Enable memory control group subsystem cmdline.txt
  replace:
    path: /boot/firmware/cmdline.txt
    regexp: '(fixrtc)$'
    replace: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  register: reboot_required
  when: cmdline_stat.stat.exists

- name: Reboot immediately if there was a change.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: reboot_required is changed

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 40
    sleep: 5
    delay: 5
    timeout: 600
  when: reboot_required is changed
