- name: install APT Transport HTTPS
  apt:
    name: apt-transport-https
    state: present

- name: Add Docker-CE cert
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker-CE repo
  apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    filename: 'docker-ce'

- name: Install Containerd
  apt:
    name: containerd
    state: present

- name: Install Docker
  apt:
    name: ['docker-ce=5:18.09.9~3-0~ubuntu-xenial', 'docker-ce-cli=5:18.09.9~3-0~ubuntu-xenial']
    state: present

- name: Docker deamon config
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0600'
  register: daemon_config

- name: add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add Kubernetes' APT repository
  apt_repository:
   repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
   state: present
   filename: 'kubernetes'

- name: install kubelet
  apt:
    name: kubelet=1.16.4-00
    state: present
    update_cache: true

- name: install kubeadm
  apt:
    name: kubeadm=1.16.4-00
    state: present

- name: Enable containerd
  service:
    name: containerd
    enabled: yes

- name: install nfs-common
  apt:
    name: nfs-common
    state: present

- name: Restart Docker
  systemd:
    name: docker
    state: restarted
  when: daemon_config is changed