- name: Check kubeadm version
  command: "kubeadm version"
  register: current_kubeadm_version

- name: Update repositories & Install new kubeadm
  shell: "apt-get update && apt-get install  -y --allow-change-held-packages kubeadm={{ kubeadm_version }}"
  when:
    - "k8s_version not in current_kubeadm_version"

- name: Check new kubeadm version
  command: "kubeadm version"
  register: new_kubeadm_version
  when:
    - "k8s_version not in current_kubeadm_version.stdout"

- name: Drain the node
  command: "kubectl drain {{ ansible_fqdn }} --ignore-daemonsets"
  when:
    - "servers[0] in ansible_fqdn"
    - "k8s_version not in current_kubeadm_version.stdout"

- name: Kubeadm upgrade plan
  command: "kubeadm upgrade plan"
  when:
    - "servers[0] in ansible_fqdn"
    - "k8s_version not in current_kubeadm_version.stdout"

- name: Kubeadm upgrade apply
  command: "kubeadm upgrade apply {{ k8s_version }} -y"
  when:
    - "servers[0] in ansible_fqdn"
    - "k8s_version not in current_kubeadm_version"

- name: Uncordon primary node
  command: "kubectl uncordon {{ ansible_fqdn }}"
  when:
    - "servers[0] in ansible_fqdn"
    - "k8s_version not in current_kubeadm_version.stdout"

- name: Drain the other nodes
  command: "kubectl drain {{ ansible_fqdn }} --ignore-daemonsets"
  when:
    - "servers[0] not in ansible_fqdn"
    - "k8s_version not in current_kubeadm_version.stdout"

- name: Upgrade other masters - apply
  command: "kubeadm upgrade node"
  when:
    - "servers[0] not in ansible_fqdn"
    - "k8s_version not in current_kubeadm_version.stdout"

- name: Uncordon primary node
  command: "kubectl uncordon {{ ansible_fqdn }}"
  when:
    - "servers[0] not in ansible_fqdn"
    - "k8s_version not in current_kubeadm_version.stdout"

- name: Upgrade kubelet and kubectl
  shell: "apt-get update && apt-get install  -y --allow-change-held-packages kubelet={{ kubeadm_version }} kubectl={{ kubeadm_version }}"
  register: kubelet_kubectl_updated
  when:
    - "k8s_version not in current_kubeadm_version.stdout"

- name: Restart kubelet
  systemd:
    name: kubelet
    state: restarted
  when:
    - kubelet_kubectl_updated.changed
